/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletest;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;
import particles.App;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
